import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields

# BRD QN-2026-0010 -> ERPNext field map. Every field is prefixed jk_ so it is
# unambiguous which customisations belong to this implementation.

CUSTOM_FIELDS = {
	# BRD-01 / BRD-03: lead + inquiry registration and representative tracking
	"Lead": [
		{"fieldname": "jk_inquiry_section", "label": "Inquiry Details", "fieldtype": "Section Break", "insert_after": "source"},
		{"fieldname": "jk_inquiry_type", "label": "Inquiry Type", "fieldtype": "Select",
		 "options": "Direct Lead\nCustomer Inquiry\nRequest\nTender", "default": "Direct Lead", "insert_after": "jk_inquiry_section"},
		{"fieldname": "jk_received_date", "label": "Date Received", "fieldtype": "Date",
		 "default": "Today", "insert_after": "jk_inquiry_type"},
		{"fieldname": "jk_inquiry_cb", "fieldtype": "Column Break", "insert_after": "jk_received_date"},
		{"fieldname": "jk_tender_ref_no", "label": "Tender / Bid Reference No", "fieldtype": "Data",
		 "depends_on": "eval:doc.jk_inquiry_type=='Tender'", "insert_after": "jk_inquiry_cb"},
		{"fieldname": "jk_requester_name", "label": "Requester Name", "fieldtype": "Data", "insert_after": "jk_tender_ref_no"},
		# Inbound capture (email / WhatsApp). Set by jk_crm.integrations.
		{"fieldname": "jk_source_channel", "label": "Captured From", "fieldtype": "Select",
		 "options": "\nManual\nEmail\nWhatsApp\nWebsite", "insert_after": "jk_requester_name",
		 "read_only": 1, "in_standard_filter": 1,
		 "description": "Channel this lead arrived through (BRD-01)."},
		{"fieldname": "jk_source_reference", "label": "Source Reference", "fieldtype": "Data",
		 "read_only": 1, "insert_after": "jk_source_channel",
		 "description": "Email address or phone number the enquiry came from."},
		{"fieldname": "jk_source_detail", "label": "Source Detail", "fieldtype": "Small Text",
		 "read_only": 1, "insert_after": "jk_source_reference"},
	],
	# BRD-01/03/04/05/21: tender registration, estimation ownership, dual deadlines
	"Opportunity": [
		{"fieldname": "jk_tender_section", "label": "Tender / Bid Details", "fieldtype": "Section Break",
		 "insert_after": "opportunity_type", "collapsible": 0},
		{"fieldname": "jk_is_tender", "label": "Is Tender / Bid", "fieldtype": "Check", "default": "0",
		 "insert_after": "jk_tender_section"},
		{"fieldname": "jk_tender_ref_no", "label": "Tender / Bid Reference No", "fieldtype": "Data",
		 "depends_on": "jk_is_tender", "insert_after": "jk_is_tender"},
		{"fieldname": "jk_customer_bid_deadline", "label": "Customer Bid Submission Deadline", "fieldtype": "Datetime",
		 "insert_after": "jk_tender_ref_no", "in_list_view": 1,
		 "description": "Date the bid must reach the customer (BRD-05)."},
		{"fieldname": "jk_requester_name", "label": "Requester / Contact Name", "fieldtype": "Data",
		 "insert_after": "jk_customer_bid_deadline"},
		{"fieldname": "jk_tender_cb", "fieldtype": "Column Break", "insert_after": "jk_requester_name"},
		{"fieldname": "jk_estimation_engineer", "label": "Estimation Engineer", "fieldtype": "Link", "options": "User",
		 "insert_after": "jk_tender_cb", "description": "Owner of the estimate (BRD-04)."},
		{"fieldname": "jk_internal_estimation_deadline", "label": "Internal Estimation Deadline", "fieldtype": "Datetime",
		 "insert_after": "jk_estimation_engineer",
		 "description": "Must fall on or before the customer deadline so review/approval can finish first (BRD-05)."},
		{"fieldname": "jk_estimation_status", "label": "Estimation Status", "fieldtype": "Select",
		 "options": "Not Started\nIn Progress\nCompleted\nSubmitted", "default": "Not Started",
		 "insert_after": "jk_internal_estimation_deadline", "in_standard_filter": 1},
		{"fieldname": "jk_estimation_completed_on", "label": "Estimation Completed On", "fieldtype": "Datetime",
		 "read_only": 1, "insert_after": "jk_estimation_status"},
	],
	# BRD-13 / BRD-33: variation orders raised as quotations against a live project
	"Quotation": [
		{"fieldname": "jk_variation_section", "label": "Variation Order", "fieldtype": "Section Break",
		 "insert_after": "order_type", "collapsible": 1},
		{"fieldname": "jk_is_variation_order", "label": "Is Variation Order", "fieldtype": "Check", "default": "0",
		 "insert_after": "jk_variation_section"},
		{"fieldname": "jk_variation_project", "label": "Against Project", "fieldtype": "Link", "options": "Project",
		 "depends_on": "jk_is_variation_order", "mandatory_depends_on": "jk_is_variation_order",
		 "insert_after": "jk_is_variation_order"},
		{"fieldname": "jk_variation_cb", "fieldtype": "Column Break", "insert_after": "jk_variation_project"},
		{"fieldname": "jk_variation_reason", "label": "Reason for Variation", "fieldtype": "Small Text",
		 "depends_on": "jk_is_variation_order", "insert_after": "jk_variation_cb"},
	],
	# BRD-18: retention terms agreed at order stage, applied at invoicing
	"Sales Order": [
		{"fieldname": "jk_retention_section", "label": "Retention Terms", "fieldtype": "Section Break",
		 "insert_after": "payment_schedule", "collapsible": 1},
		{"fieldname": "jk_has_retention", "label": "Retention Applicable", "fieldtype": "Check", "default": "0",
		 "insert_after": "jk_retention_section"},
		{"fieldname": "jk_retention_percentage", "label": "Retention %", "fieldtype": "Percent",
		 "depends_on": "jk_has_retention", "insert_after": "jk_has_retention"},
		{"fieldname": "jk_retention_cb", "fieldtype": "Column Break", "insert_after": "jk_retention_percentage"},
		{"fieldname": "jk_retention_period_days", "label": "Retention Period (Days)", "fieldtype": "Int",
		 "depends_on": "jk_has_retention", "insert_after": "jk_retention_cb",
		 "description": "Days after final invoice before retention is released (BRD-18)."},
		{"fieldname": "jk_retention_amount", "label": "Retention Amount", "fieldtype": "Currency", "read_only": 1,
		 "depends_on": "jk_has_retention", "insert_after": "jk_retention_period_days"},
	],
	# BRD-09/10/11/12/20/23/32: project identity, ownership, handover, warranty, PO closure
	"Project": [
		{"fieldname": "jk_identity_section", "label": "Project Identity & Ownership", "fieldtype": "Section Break",
		 "insert_after": "project_name"},
		{"fieldname": "jk_project_code", "label": "Project Code", "fieldtype": "Data", "unique": 1,
		 "insert_after": "jk_identity_section", "in_list_view": 1, "in_standard_filter": 1,
		 "description": "Internal project code, deliberately separate from the customer PO number (BRD-09)."},
		{"fieldname": "jk_customer_po_no", "label": "Customer Purchase Order No", "fieldtype": "Data",
		 "insert_after": "jk_project_code"},
		{"fieldname": "jk_customer_po_status", "label": "Customer PO Status", "fieldtype": "Select",
		 "options": "Open\nWork Completed\nClosed", "default": "Open", "insert_after": "jk_customer_po_no",
		 "in_standard_filter": 1, "description": "BRD-32 completion/closure control."},
		{"fieldname": "jk_identity_cb", "fieldtype": "Column Break", "insert_after": "jk_customer_po_status"},
		{"fieldname": "jk_project_manager", "label": "Project Manager", "fieldtype": "Link", "options": "User",
		 "insert_after": "jk_identity_cb", "in_standard_filter": 1, "description": "BRD-10."},
		{"fieldname": "jk_site_supervisor", "label": "Site Supervisor", "fieldtype": "Link", "options": "User",
		 "insert_after": "jk_project_manager"},
		{"fieldname": "jk_site_address", "label": "Delivery / Site Address", "fieldtype": "Link", "options": "Address",
		 "insert_after": "jk_site_supervisor", "description": "BRD-20 third address concept."},
		# BRD-11 handover
		{"fieldname": "jk_handover_section", "label": "Sales to Project Handover", "fieldtype": "Section Break",
		 "insert_after": "jk_site_address", "collapsible": 1},
		{"fieldname": "jk_handover_status", "label": "Handover Status", "fieldtype": "Select",
		 "options": "Not Started\nPending Handover\nHandover Accepted", "default": "Not Started",
		 "insert_after": "jk_handover_section", "in_standard_filter": 1},
		{"fieldname": "jk_handover_from", "label": "Handed Over By (Sales)", "fieldtype": "Link", "options": "User",
		 "insert_after": "jk_handover_status"},
		{"fieldname": "jk_handover_cb", "fieldtype": "Column Break", "insert_after": "jk_handover_from"},
		{"fieldname": "jk_handover_to", "label": "Accepted By (Projects)", "fieldtype": "Link", "options": "User",
		 "insert_after": "jk_handover_cb"},
		{"fieldname": "jk_handover_date", "label": "Handover Date", "fieldtype": "Date", "insert_after": "jk_handover_to"},
		{"fieldname": "jk_handover_checklist_sb", "fieldtype": "Section Break", "insert_after": "jk_handover_date"},
		{"fieldname": "jk_handover_checklist", "label": "Handover Checklist", "fieldtype": "Table",
		 "options": "JK Project Handover Item", "insert_after": "jk_handover_checklist_sb"},
		# BRD-23 warranty
		{"fieldname": "jk_warranty_section", "label": "Warranty / Guarantee", "fieldtype": "Section Break",
		 "insert_after": "jk_handover_checklist", "collapsible": 1},
		{"fieldname": "jk_has_warranty", "label": "Warranty Applicable", "fieldtype": "Check", "default": "0",
		 "insert_after": "jk_warranty_section"},
		{"fieldname": "jk_warranty_start_date", "label": "Warranty Start Date", "fieldtype": "Date",
		 "depends_on": "jk_has_warranty", "insert_after": "jk_has_warranty"},
		{"fieldname": "jk_warranty_period_months", "label": "Warranty Period (Months)", "fieldtype": "Int",
		 "depends_on": "jk_has_warranty", "insert_after": "jk_warranty_start_date"},
		{"fieldname": "jk_warranty_cb", "fieldtype": "Column Break", "insert_after": "jk_warranty_period_months"},
		{"fieldname": "jk_warranty_end_date", "label": "Warranty End Date", "fieldtype": "Date", "read_only": 1,
		 "depends_on": "jk_has_warranty", "insert_after": "jk_warranty_cb"},
		{"fieldname": "jk_warranty_terms", "label": "Warranty Terms", "fieldtype": "Small Text",
		 "depends_on": "jk_has_warranty", "insert_after": "jk_warranty_end_date"},
		{"fieldname": "jk_warranty_status", "label": "Warranty Status", "fieldtype": "Select",
		 "options": "\nNot Applicable\nNot Started\nActive\nExpired", "read_only": 1,
		 "depends_on": "jk_has_warranty", "insert_after": "jk_warranty_terms",
		 "in_standard_filter": 1,
		 "description": "Maintained automatically from the warranty dates (BRD-23)."},
		# BRD-15: project completion documentation
		{"fieldname": "jk_completion_section", "label": "Completion Certificate", "fieldtype": "Section Break",
		 "insert_after": "jk_warranty_status", "collapsible": 1},
		{"fieldname": "jk_completion_certificate_no", "label": "Completion Certificate No", "fieldtype": "Data",
		 "read_only": 1, "insert_after": "jk_completion_section",
		 "description": "Generated when the certificate is issued (BRD-15)."},
		{"fieldname": "jk_completion_date", "label": "Completion Date", "fieldtype": "Date",
		 "insert_after": "jk_completion_certificate_no"},
		{"fieldname": "jk_completion_cb", "fieldtype": "Column Break", "insert_after": "jk_completion_date"},
		{"fieldname": "jk_certificate_issued_by", "label": "Issued By", "fieldtype": "Link", "options": "User",
		 "insert_after": "jk_completion_cb"},
		{"fieldname": "jk_certificate_accepted_by", "label": "Accepted By (Customer)", "fieldtype": "Data",
		 "insert_after": "jk_certificate_issued_by"},
		{"fieldname": "jk_completion_notes", "label": "Completion Notes", "fieldtype": "Small Text",
		 "insert_after": "jk_certificate_accepted_by"},
	],
	# BRD-16/17/18/24: billing type, retention, status tracking, ZATCA fields
	"Sales Invoice": [
		{"fieldname": "jk_billing_section", "label": "Project Billing", "fieldtype": "Section Break",
		 "insert_after": "project", "collapsible": 0},
		{"fieldname": "jk_billing_type", "label": "Billing Type", "fieldtype": "Select",
		 "options": "Standard\nAdvance\nProgress\nFinal\nRetention Release", "default": "Standard",
		 "insert_after": "jk_billing_section", "in_standard_filter": 1, "description": "BRD-17."},
		{"fieldname": "jk_progress_percentage", "label": "Progress Billed %", "fieldtype": "Percent",
		 "depends_on": "eval:doc.jk_billing_type=='Progress'", "insert_after": "jk_billing_type"},
		{"fieldname": "jk_billing_cb", "fieldtype": "Column Break", "insert_after": "jk_progress_percentage"},
		{"fieldname": "jk_invoice_status", "label": "Invoice Status", "fieldtype": "Select",
		 "options": "Pending\nSubmitted\nApproved\nPaid\nOverdue", "default": "Pending", "read_only": 1,
		 "insert_after": "jk_billing_cb", "in_list_view": 1, "in_standard_filter": 1, "allow_on_submit": 1,
		 "description": "BRD-16, maintained automatically from docstatus, workflow and payment state."},
		{"fieldname": "jk_retention_sb", "label": "Retention", "fieldtype": "Section Break",
		 "insert_after": "jk_invoice_status", "collapsible": 1},
		{"fieldname": "jk_retention_percentage", "label": "Retention %", "fieldtype": "Percent",
		 "insert_after": "jk_retention_sb"},
		{"fieldname": "jk_retention_amount", "label": "Retention Amount Withheld", "fieldtype": "Currency",
		 "read_only": 1, "insert_after": "jk_retention_percentage"},
		{"fieldname": "jk_retention_cb", "fieldtype": "Column Break", "insert_after": "jk_retention_amount"},
		{"fieldname": "jk_retention_release_date", "label": "Retention Release Due Date", "fieldtype": "Date",
		 "insert_after": "jk_retention_cb"},
		{"fieldname": "jk_retention_released", "label": "Retention Released", "fieldtype": "Check", "default": "0",
		 "read_only": 1, "allow_on_submit": 1, "insert_after": "jk_retention_release_date"},
		# BRD-24 ZATCA - demo/simulation fields, populated by the compliance app in production
		{"fieldname": "jk_zatca_section", "label": "ZATCA / Saudi VAT", "fieldtype": "Section Break",
		 "insert_after": "jk_retention_released", "collapsible": 1},
		{"fieldname": "jk_zatca_status", "label": "ZATCA Status", "fieldtype": "Select",
		 "options": "Not Applicable\nPending\nSimulated (Demo)\nCleared\nFailed", "default": "Pending",
		 "read_only": 1, "allow_on_submit": 1, "insert_after": "jk_zatca_section"},
		{"fieldname": "jk_zatca_uuid", "label": "ZATCA Invoice UUID", "fieldtype": "Data", "read_only": 1,
		 "allow_on_submit": 1, "insert_after": "jk_zatca_status"},
		{"fieldname": "jk_zatca_cb", "fieldtype": "Column Break", "insert_after": "jk_zatca_uuid"},
		{"fieldname": "jk_zatca_hash", "label": "Invoice Hash", "fieldtype": "Data", "read_only": 1,
		 "allow_on_submit": 1, "insert_after": "jk_zatca_cb"},
		{"fieldname": "jk_zatca_qr", "label": "TLV QR (Base64)", "fieldtype": "Small Text", "read_only": 1,
		 "allow_on_submit": 1, "insert_after": "jk_zatca_hash"},
	],
	# BRD-14: procurement is not restricted to stock items
	"Purchase Order": [
		{"fieldname": "jk_procurement_section", "label": "Project Procurement", "fieldtype": "Section Break",
		 "insert_after": "order_confirmation_date", "collapsible": 1},
		{"fieldname": "jk_project", "label": "Project", "fieldtype": "Link", "options": "Project",
		 "insert_after": "jk_procurement_section", "in_standard_filter": 1},
		{"fieldname": "jk_procurement_cb", "fieldtype": "Column Break", "insert_after": "jk_project"},
		{"fieldname": "jk_procurement_category", "label": "Procurement Category", "fieldtype": "Select",
		 "options": "Material\nService\nSubcontracting\nConsumables\nRental\nOther", "default": "Material",
		 "insert_after": "jk_procurement_cb", "in_standard_filter": 1, "description": "BRD-14."},
	],
	# BRD-20: legal / registered entity address kept distinct from billing and site
	"Customer": [
		{"fieldname": "jk_address_section", "label": "Statutory Details", "fieldtype": "Section Break",
		 "insert_after": "tax_category", "collapsible": 1},
		{"fieldname": "jk_legal_entity_address", "label": "Legal / Registered Address", "fieldtype": "Link",
		 "options": "Address", "insert_after": "jk_address_section"},
		{"fieldname": "jk_address_cb", "fieldtype": "Column Break", "insert_after": "jk_legal_entity_address"},
		{"fieldname": "jk_cr_number", "label": "Commercial Registration No", "fieldtype": "Data",
		 "insert_after": "jk_address_cb"},
	],
}


def execute():
	create_custom_fields(CUSTOM_FIELDS, update=True)
	frappe.db.commit()
	total = sum(len(v) for v in CUSTOM_FIELDS.values())
	print(f"Created/updated {total} custom fields across {len(CUSTOM_FIELDS)} doctypes.")
